export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_SIGNOUT = "USER_SIGNIN_SIGNOUT";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_REMOVE = "USER_REGISTER_REMOVE";

export const MATCH_ALLMATCH_REQUEST = "MATCH_ALLMATCH_REQUEST";
export const MATCH_ALLMATCH_SUCCESS = "MATCH_ALLMATCH_SUCCESS";
export const MATCH_ALLMATCH_FAIL = "MATCH_ALLMATCH_FAIL";

export const TEAM_ALLTEAM_REQUEST = "TEAM_ALLTEAM_REQUEST";
export const TEAM_ALLTEAM_SUCCESS = "TEAM_ALLTEAM_SUCCESS";
export const TEAM_ALLTEAM_FAIL = "TEAM_ALLTEAM_FAIL";

export const LOCATION_ALLLOCATION_REQUEST = "LOCATION_ALLLOCATION_REQUEST";
export const LOCATION_ALLLOCATION_SUCCESS = "LOCATION_ALLLOCATION_SUCCESS";
export const LOCATION_ALLLOCATION_FAIL = "LOCATION_ALLLOCATION_FAIL";
